# Environment settings
env_id: "Pendulum-v1"

# === ADD THESE LINES ===
agent_module: "sac_cas.sac_cas_agent"  # Path to the agent module relative to 'dsac' package
agent_class: "SacCasAgent"              # Class name of the agent
# =======================

# Trainer settings
# training_total_timesteps: 50000 # This was from the CartPole example, adjust for Pendulum
training_total_timesteps: 100000 # Pendulum might need more
max_steps_per_episode: 200      
log_interval_timesteps: 2000    
eval_frequency_timesteps: 5000  
n_eval_episodes: 5              
save_freq_episodes: 50         
log_root: "dsac/data/runs/sac"     
model_root: "dsac/data/models/sac"   

# Agent Hyperparameters
use_encoder: False                  
encoder_mlp_hidden_dims: []         
hidden_dims_actor_body: [256, 256]  # Default from previous discussions
hidden_dims_critic_body: [256, 256] # Default from previous discussions

gamma: 0.99                     
tau: 0.005                      
alpha_init: "auto"                   
critic_lr: 0.0003               
actor_lr: 0.0003                
replay_buffer_size: 1000000     
batch_size: 256                 
learning_starts: 1000           
gradient_steps: 1               
policy_delay: 2                 
max_grad_norm: 1.0              # Or null to disable
reward_scale: 1.0               
aux_data_specs_for_buffer: null